system:
  addr: 0.0.0.0
  port: 8091
  mode: debug
data:
  mysql:
    addr: 127.0.0.1
    port: 3306
    db: xx
    user: xxx
    passwd: xxx
  redis:
    addr: 127.0.0.1
    port: 6379
    db: 0
    auth: xxxx
